kind: pipeline
name: default

services:
  - name: postgres
    image: postgres:14
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres

steps:
  - name: restore-cache
    image: meltwater/drone-cache
    pull: true
    settings:
      backend: 'filesystem'
      restore: true
      cache_key: 'volume'
      archive_format: 'gzip'
      cache_key: '{{ checksum "mix.lock" }}'
      mount:
        - 'deps'
    volumes:
      - name: cache
        path: /tmp/cache
  - name: get-deps
    image: elixir:1.13
    commands:
      - mix local.rebar --force
      - mix local.hex --force
      - mix deps.get
      - mix compile
 - name: rebuild-cache
    image: meltwater/drone-cache
    pull: true
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: "volume"
      archive_format: "gzip"
      cache_key: '{{ checksum "mix.lock" }}'
      mount:
        - 'deps'
    volumes:
    - name: cache
      path: /tmp/cache

  - name: test
    image: elixir:1.13
    environment:
      POSTGRES_HOST: postgres
    commands:
      - mix test

volumes:
  - name: cache
    host:
      path: /var/lib/cache
